import type React from "react";

const commonStyles: Record<string, React.CSSProperties> = {
  mainContainer: {
    minHeight: "100vh",
    backgroundColor: "var(--background, #F6F8FB)",
    color: "var(--texto, #162032)",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    padding: "20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
  },
  headerTitle: {
    fontSize: "1.5rem",
    margin: 0,
  },
  headerSubtitle: {
    fontSize: "0.95rem",
    margin: 0,
    color: "var(--texto-muted, #475467)",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  helpButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    borderRadius: "999px",
    padding: "8px 14px",
    background: "var(--panel-bg, #FFFFFF)",
    cursor: "pointer",
    fontSize: "14px",
  },
  themeToggle: {
    display: "flex",
    gap: "6px",
    borderRadius: "999px",
    padding: "4px",
    backgroundColor: "var(--toggle-bg, rgba(15, 23, 42, 0.06))",
  },
  themeButton: {
    border: "none",
    background: "transparent",
    cursor: "pointer",
    borderRadius: "999px",
    width: "34px",
    height: "34px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--toggle-inactive, #94A3B8)",
  },
  languageToggle: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 16px",
    borderRadius: "999px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    background: "var(--panel-bg, #FFFFFF)",
    fontSize: "14px",
  },
  modeTabsContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
    padding: "0 20px 10px",
  },
  modeTab: {
    border: "1px solid var(--panel-border, #e0e0e0)",
    borderRadius: "12px",
    padding: "10px 16px",
    background: "var(--panel-bg, #FFFFFF)",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.95rem",
  },
  panelContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "0 20px 20px",
    gap: "16px",
  },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "0 20px 20px",
    gap: "16px",
  },
  modePanel: {
    backgroundColor: "var(--panel-bg, #FFFFFF)",
    borderRadius: "20px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    padding: "18px",
    minHeight: "360px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  modeTitle: {
    margin: 0,
    fontSize: "1.1rem",
  },
  modeDescription: {
    margin: 0,
    color: "var(--texto-muted, #475467)",
    fontSize: "0.9rem",
  },
  twoFrameContainer: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "18px",
    height: "520px",
  },
  twoFrameContainerMobile: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  inputFrame: {
    background: "var(--panel-bg, #FFFFFF)",
    borderRadius: "16px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  inputFrameMobile: {
    background: "var(--panel-bg, #FFFFFF)",
    borderRadius: "16px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  outputFrame: {
    background: "var(--panel-bg, #FFFFFF)",
    borderRadius: "16px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  outputFrameMobile: {
    background: "var(--panel-bg, #FFFFFF)",
    borderRadius: "16px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  frameTitle: {
    margin: 0,
    fontSize: "1rem",
    marginBottom: "8px",
  },
  textarea: {
    width: "100%",
    minHeight: "160px",
    borderRadius: "12px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    padding: "12px",
    fontSize: "1rem",
    resize: "vertical" as const,
    background: "var(--input-bg, #FFFFFF)",
    color: "var(--texto, #162032)",
  },
  select: {
    borderRadius: "10px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    padding: "8px 10px",
    fontSize: "0.95rem",
    background: "var(--input-bg, #FFFFFF)",
    color: "var(--texto, #162032)",
  },
  label: {
    fontWeight: 600,
    color: "var(--texto, #162032)",
  },
  checkboxRow: {
    display: "flex",
    flexWrap: "wrap",
  },
  checkboxChip: {
    border: "1px solid var(--panel-border, #e0e0e0)",
    borderRadius: "10px",
    padding: "6px 12px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "var(--muted-surface, #f7f9fb)",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "var(--texto, #162032)",
  },
  sliderControl: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  generateButton: {
    border: "none",
    borderRadius: "12px",
    background:
      "linear-gradient(120deg, var(--primary, #6366F1), var(--secondary, #8B5CF6))",
    color: "#fff",
    padding: "12px",
    fontSize: "1rem",
    cursor: "pointer",
    fontWeight: 600,
    transition: "opacity 0.2s",
  },
  outputSection: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  outputGrid: {
    display: "grid",
    gap: "12px",
  },
  outputCard: {
    border: "1px solid var(--panel-border, #e0e0e0)",
    borderRadius: "12px",
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    backgroundColor: "var(--muted-surface, #f7f9fb)",
  },
  copyButton: {
    borderRadius: "10px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    background: "var(--panel-bg, #FFFFFF)",
    padding: "8px 12px",
    cursor: "pointer",
    alignSelf: "flex-end",
  },
  loadingMessage: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "6px",
    fontSize: "0.95rem",
    color: "var(--texto, #162032)",
  },
  errorMessage: {
    backgroundColor: "rgba(239, 68, 68, 0.08)",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    color: "#b91c1c",
    padding: "10px",
    borderRadius: "10px",
    fontSize: "0.9rem",
  },
  spinner: {
    width: "30px",
    height: "30px",
    borderRadius: "999px",
    border: "3px solid rgba(99, 102, 241, 0.2)",
    borderTopColor: "var(--primary, #6366F1)",
    animation: "spin 1s linear infinite",
  },
  chatContainer: {
    border: "1px solid var(--panel-border, #e0e0e0)",
    borderRadius: "12px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    backgroundColor: "var(--panel-bg, #FFFFFF)",
    height: "360px",
    overflowY: "auto",
  },
  chatMessage: {
    padding: "10px 14px",
    borderRadius: "12px",
    width: "fit-content",
    maxWidth: "80%",
    fontSize: "0.95rem",
  },
  userMessage: {
    alignSelf: "flex-end",
    backgroundColor: "var(--primary, #6366F1)",
    color: "#fff",
  },
  aiMessage: {
    alignSelf: "flex-start",
    backgroundColor: "var(--muted-surface, #f7f9fb)",
  },
  chatInputRow: {
    display: "flex",
    gap: "8px",
  },
  chatTextInput: {
    flex: 1,
    border: "1px solid var(--panel-border, #e0e0e0)",
    borderRadius: "12px",
    padding: "10px",
    minHeight: "60px",
    backgroundColor: "var(--input-bg, #FFFFFF)",
    color: "var(--texto, #162032)",
    minWidth: 0,
    width: "100%",
  },
  chatCounters: {
    width: "100%",
    display: "flex",
    justifyContent: "flex-end",
    fontSize: "12px",
    color: "var(--texto, #162032)",
    opacity: 0.85,
    paddingRight: "0",
  },
  helpOverlay: {
    position: "fixed" as const,
    inset: 0,
    backgroundColor: "rgba(15,23,42,0.55)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "20px",
    zIndex: 1000,
  },
  helpModal: {
    backgroundColor: "var(--panel-bg, #FFFFFF)",
    borderRadius: "16px",
    padding: "24px",
    width: "min(520px, 90vw)",
    boxShadow: "0 25px 65px rgba(15, 23, 42, 0.35)",
    border: "1px solid var(--panel-border, #e0e0e0)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  helpModalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
  },
  helpModalList: {
    margin: 0,
    paddingLeft: "18px",
    color: "var(--texto, #162032)",
  },
  helpCloseButton: {
    border: "none",
    background: "transparent",
    fontSize: "24px",
    cursor: "pointer",
    color: "var(--texto, #162032)",
  },
  helpIntro: {
    margin: 0,
    color: "var(--texto, #162032)",
    opacity: 0.8,
  },
  inputCounter: {
    alignSelf: "flex-end",
    fontSize: "12px",
    color: "var(--toggle-inactive-text, #667085)",
    marginTop: "4px",
    paddingRight: "0",
  },
  liveTranscript: {
    border: "1px solid var(--panel-border, #e0e0e0)",
    borderRadius: "12px",
    padding: "12px",
    minHeight: "120px",
    backgroundColor: "var(--muted-surface, #f7f9fb)",
    flex: 1,
    overflowY: "auto",
    width: "100%",
    boxSizing: "border-box",
  },
  audioPlayer: {
    width: "100%",
    marginTop: "10px",
  },
  settingsBar: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "16px",
    borderTop: "1px solid var(--panel-border, #e0e0e0)",
    paddingTop: "12px",
    marginTop: "12px",
    flexWrap: "wrap",
  },
  settingsGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  settingsLabel: {
    fontSize: "0.85rem",
    fontWeight: 600,
    color: "var(--texto-muted, #475467)",
  },
  resetButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    borderRadius: "12px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    padding: "8px 14px",
    background: "var(--panel-bg, #FFFFFF)",
    cursor: "pointer",
  },
  tabNavigation: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginBottom: "16px",
  },
  tabButton: {
    borderRadius: "999px",
    border: "1px solid var(--panel-border, #e0e0e0)",
    padding: "8px 18px",
    backgroundColor: "var(--panel-bg, #FFFFFF)",
    cursor: "pointer",
    fontWeight: 600,
    transition: "background-color 0.2s",
  },
  tabButtonActive: {
    background:
      "linear-gradient(120deg, var(--primary, #6366F1), var(--secondary, #8B5CF6))",
    color: "#fff",
    borderColor: "transparent",
  },
  modeScrollArea: {
    width: "100%",
  },
};

export default commonStyles;
